name: Build/release

on: push

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      # https://github.com/actions/setup-node/issues/531
      SKIP_YARN_COREPACK_CHECK: true

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install pkg
        run: npm i -g pkg

      - name: Frontend yarn
        run: cd ezshare-frontend && yarn

      - name: yarn
        run: yarn

      - name: Build
        run: yarn build

      - name: Patch
        run: patch -p1 < standalone.patch

      - name: Run pkg
        run: |
          mkdir win macos linux
          mkdir win/ezshare linux/ezshare
          mv node_modules/clipboardy/fallbacks/windows/clipboard_x86_64.exe win/ezshare/clipboard.exe
          mv node_modules/clipboardy/fallbacks/linux/xsel linux/ezshare/clipboard
          rm -r node_modules/clipboardy/fallbacks
          pkg .
          mv ezshare-win.exe win/ezshare/ezshare.exe
          mv ezshare-linux linux/ezshare/ezshare
          mv ezshare-macos macos/ezshare
          cd win
          zip -r ../ezshare-win.zip ezshare
          cd ..
          cd macos
          zip ../ezshare-macos.zip ezshare
          cd ..
          cd linux
          zip -r ../ezshare-linux.zip ezshare

      - name: (Windows) Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Binaries
          path: |
            ezshare-win.zip
            ezshare-macos.zip
            ezshare-linux.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ezshare-win.zip
            ezshare-macos.zip
            ezshare-linux.zip
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
